### ISSUE TITLE
Compatibility with Neos 5.0

### ISSUE THREAD

**Issue by jonnitto** [t3n/neos-debug#37]
I really love this package! Thank you a lot for your awesome work. Unfortunately, it is not yet ready for Neos 5.0. Are there any plans?

**Comment by drlimbo** [comment]
Looks like @markuspfeifenberger tried to here https://github.com/t3n/neos-debug/pull/44

**Comment by johannessteu** [comment]
https://github.com/t3n/neos-debug/releases/tag/1.0.0

:)
